export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";
export const FETCH_SEARCH_POST = "FETCH_SEARCH_POST";
export const FETCH_PARTIAL_SEARCH_POST = "FETCH_PARTIAL_SEARCH_POST";
export const PATCH_POST = "PATCH_POST";
